on:
    push:
        tags:
            - '[0-9]+.[0-9]+.[0-9]+'

name: Deploy Application
jobs:
    set-version-tags:
        name: Set version tags
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.prepare-version-tags.outputs.version }}
            tags: ${{ steps.prepare-version-tags.outputs.tags }}
            rc-commit-id: ${{ steps.save-acceptance-commit-id.outputs.rc-commit-id }}
        steps:
            - name: Prepare image version and tags
              id: prepare-version-tags
              run: |
                  DOCKER_IMAGE=derp
                  VERSION=${GITHUB_REF#refs/tags/}
                  VERSION=${VERSION//\//-}
                  TAGS="${DOCKER_IMAGE}:${VERSION}"

                  MINOR=${VERSION%.*}
                  MAJOR=${MINOR%.*}
                  TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"

                  echo "version=${VERSION}" >> $GITHUB_OUTPUT
                  echo "tags=${TAGS}" >> $GITHUB_OUTPUT
            - uses: actions/checkout@v3
              with:
                  ref: ${{ steps.prepare-version-tags.outputs.version }}rc
                  fetch-depth: 0
            - name: Save Acceptance Commit ID
              id: save-acceptance-commit-id
              run:
                echo "rc-commit-id=$(git log -1 --pretty=format:"%H")" >> $GITHUB_OUTPUT

    action:
        name: Run debug action
        runs-on: ubuntu-latest
        needs:
            - set-version-tags
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: run workflow
              run: |
                  echo $(git log -1 --pretty=format:"%H")
                  echo ${{ needs.set-version-tags.outputs.rctag }}