on:
  push:
    branches:
      - '*'

jobs:
  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: colpal/actions-clean@v1
      - uses: actions/checkout@v4
      - name: Cache Image
        id: cache-image
        uses: actions/cache@v3
        with:
          key: test-${{ github.run_id }}
          path: .docker/test-${{ github.run_id }}.tar
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: docker pull ghcr.io/jbleijenberg-ehvg/tag-fest:cache
      - name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-from: |
            type=registry,ref=php:8.3-alpine
            type=registry,ref=ghcr.io/jbleijenberg-ehvg/tag-fest:cache
          tags: test:${{ github.run_id }}
          outputs: type=docker,dest=.docker/test-${{ github.run_id }}.tar