name: Publish to Production

on:
  push:
    tags:
      - '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
      
jobs:
  deploy:
    name: "Deploy application"
    runs-on: ubuntu-24.04
    steps:
      - run: "echo ${{ github.ref_name }}"