name: Publish to Production

on:
  push:
    tags:
      - '*'
      
jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check tag name
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          if [[ ! "$TAG_NAME" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}-rc ]]; then
            echo "❌ Invalid tag name: $TAG_NAME"
            exit 1
          else
            echo "✅ Valid tag: $TAG_NAME"
          fi