on:
  release:
    types:
      - prereleased

jobs:
  set-version-tags:
    name: Set version tags
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prepare-version-tags.outputs.version }}

    steps:
      - name: Prepare image version and tags
        id: prepare-version-tags
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION//\//-}
          
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  etst:
    name: Prepare build environment
    runs-on: ubuntu-latest
    needs:
      - set-verison-tags
    steps:
      - name: derp
        run: |
          echo ${{ needs.set-version-tags.outputs.version }}
