name: Publish to Pre Prod

on:
  push:
    branches:
      - '*'
      
jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get Workflow Job URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          jobs_url="${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs"
          job_name="${{ github.job }}"
          job_id=$(curl -sSf "$jobs_url" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            | jq --arg job_name "$job_name" '.jobs[] | select(.name == $job_name) | .id')
          echo "Job ID: $job_id"
          echo "Job URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/$job_id"